CREATE TABLE BUSINESS_SERVICE (
  BUSINESS_SERVICE_ID  VARCHAR(20)  NOT NULL,
  CAPTION              VARCHAR(80)  NOT NULL
);

ALTER TABLE BUSINESS_SERVICE
  ADD CONSTRAINT BUSINESS_SERVICE_PK
      PRIMARY KEY (BUSINESS_SERVICE_ID);



CREATE TABLE BUSINESS_CUSTOMER (
  BUSINESS_CUSTOMER_ID VARCHAR(20)  NOT NULL,
  CAPTION              VARCHAR(80)  NOT NULL,
  ADDRESS              VARCHAR(255),
  WEBSITE              VARCHAR(80),
  PHONE                VARCHAR(20),
  FAX                  VARCHAR(20),
  LONGITUDE            FLOAT,
  LATITUDE             FLOAT,
  ALTITUDE             FLOAT
);

ALTER TABLE BUSINESS_CUSTOMER
  ADD CONSTRAINT BUSINESS_CUSTOMER_PK
      PRIMARY KEY (BUSINESS_CUSTOMER_ID);



CREATE TABLE BUSINESS_CONTRACT (
  BUSINESS_SERVICE_ID  VARCHAR(20)   NOT NULL,
  BUSINESS_CUSTOMER_ID VARCHAR(20)   NOT NULL,
  BEGDA                TIMESTAMP     NOT NULL,
  ENDDA                TIMESTAMP     NOT NULL,
  COST                 FLOAT,
  DESCRIPTION          VARCHAR(2000)
);

ALTER TABLE BUSINESS_CONTRACT
  ADD CONSTRAINT BUSINESS_CONTRACT_PK
      PRIMARY KEY(BUSINESS_SERVICE_ID, BUSINESS_CUSTOMER_ID, BEGDA);

ALTER TABLE BUSINESS_CONTRACT
  ADD CONSTRAINT BUSINESS_CONTRACT_FK1
      FOREIGN KEY(BUSINESS_SERVICE_ID)   REFERENCES BUSINESS_SERVICE  (BUSINESS_SERVICE_ID);

ALTER TABLE BUSINESS_CONTRACT
  ADD CONSTRAINT BUSINESS_CONTRACT_FK2
      FOREIGN KEY(BUSINESS_CUSTOMER_ID)  REFERENCES BUSINESS_CUSTOMER (BUSINESS_CUSTOMER_ID);

CREATE INDEX BUSINESS_CONTRACT_IND1 ON BUSINESS_CONTRACT (BUSINESS_CUSTOMER_ID);



CREATE TABLE SERVICE_CUSTOMER (
  SERVICE_CUSTOMER_ID  INTEGER      NOT NULL,
  BUSINESS_CUSTOMER_ID VARCHAR(20)  NOT NULL,
  CAPTION              VARCHAR(80)  NOT NULL,
  ADDRESS              VARCHAR(255) NOT NULL,
  WEB_SITE             VARCHAR(80),
  PHONE                VARCHAR(20),
  FAX                  VARCHAR(20),
  LONGITUDE            FLOAT,
  LATITUDE             FLOAT,
  ALTITUDE             FLOAT
);

ALTER TABLE SERVICE_CUSTOMER
  ADD CONSTRAINT SERVICE_CUSTOMER_PK
      PRIMARY KEY (SERVICE_CUSTOMER_ID);

CREATE SEQUENCE SERVICE_CUSTOMER_ID_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE SERVICE_CUSTOMER
  ADD CONSTRAINT SERVICE_CUSTOMER_FK
      FOREIGN KEY(BUSINESS_CUSTOMER_ID)  REFERENCES BUSINESS_CUSTOMER (BUSINESS_CUSTOMER_ID);

CREATE INDEX SERVICE_CUSTOMER_IND1 ON SERVICE_CUSTOMER (BUSINESS_CUSTOMER_ID);



CREATE TABLE CUSTOMER_ADDRESS (
  SERVICE_CUSTOMER_ID  INTEGER       NOT NULL,
  ADDRESS_TYPE         VARCHAR(1)    NOT NULL,
  ADDRESS_ID           SMALLINT      NOT NULL,
  ADDRESS              VARCHAR(80)   NOT NULL,
  CITY                 VARCHAR(20)   NOT NULL,
  STATE                VARCHAR(2),
  COUNTRY              VARCHAR(2),
  LONGITUDE            FLOAT,
  LATITUDE             FLOAT,
  ALTITUDE             FLOAT
);

ALTER TABLE CUSTOMER_ADDRESS
  ADD CONSTRAINT CUSTOMER_ADDRESS_PK
      PRIMARY KEY(SERVICE_CUSTOMER_ID, ADDRESS_TYPE, LINE);

ALTER TABLE CUSTOMER_ADDRESS
  ADD CONSTRAINT CUSTOMER_ADDRESS_FK1
      FOREIGN KEY(SERVICE_CUSTOMER_ID)
      REFERENCES SERVICE_CUSTOMER(SERVICE_CUSTOMER_ID);



INSERT INTO DOMAIN_NAME (DOMAIN, KEYSIZE, CAPTION, SORT_BY) VALUES ('ADDRESS_TYPE', 1, 'ADDRESS_TYPE', 'K');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'D', 'DELIVERY ADDRESS');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'H', 'HEAD QUARTERS');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'S', 'SALES STORE');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'W', 'WAREHOUSE');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'B', 'BRANCH');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'I', 'INVOICE ADDRESS');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'M', 'MAINTENANCE CENTER');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'P', 'PRODUCTION CENTER');
INSERT INTO DOMAIN_VALUE (DOMAIN, REFVALUE, CAPTION) VALUES ('ADDRESS_TYPE', 'F', 'FOREWARD SALES POINT');

INSERT INTO DOMAIN_LOOKUP (TABLENAME, FIELDNAME, DOMAIN) VALUES ('CUSTOMER_ADDRESS', 'ADDRESS_TYPE', 'ADDRESS_TYPE');



INSERT INTO MAIN_MENU (MENU, CAPTION, ICON, DISPLAY_ORDER) VALUES ('BUSINESS_ADMIN',  'BUSINESS_ADMIN', 'fa-circle', 9800);

INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('BUSINESS_SERVICE',  'BUSINESS_SERVICE',  'fa-circle',        'businessService/list',        'BUSINESS_ADMIN', 10);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('BUSINESS_CUSTOMER', 'BUSINESS_CUSTOMER', 'fa-circle',        'businessCustomer/list',       'BUSINESS_ADMIN', 20);
INSERT INTO SCREEN_PAGE (PAGENAME,CAPTION,ICON,URL,MENU,DISPLAY_ORDER) VALUES ('CUSTOMER',          'CUSTOMER',          'fa-circle',        'customer/list',               'BUSINESS_ADMIN', 30);



INSERT INTO AUTHORITY_OBJECT (OBJECT_TYPE) VALUES ('BUSINESS_CONTRACT');

INSERT INTO AUTHORITY_OBJECT_ACTION (OBJECT_TYPE,ACTION) VALUES ('BUSINESS_CONTRACT',  'INITIALIZE');
INSERT INTO AUTHORITY_OBJECT_ACTION (OBJECT_TYPE,ACTION) VALUES ('BUSINESS_CONTRACT',  'FINALIZE');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'BUSINESS_CONTRACT', 'INITIALIZE', '*');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'BUSINESS_CONTRACT', 'FINALIZE',   '*');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'PAGE', 'ACCESS', 'BUSINESS_SERVICE');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'PAGE', 'ACCESS', 'BUSINESS_CUSTOMER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'PAGE', 'ACCESS', 'PERSON');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'SELECT', 'BUSINESS_SERVICE' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'SELECT', 'BUSINESS_CUSTOMER' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'SELECT', 'BUSINESS_CONTRACT' );

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'INSERT', 'BUSINESS_SERVICE' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'INSERT', 'BUSINESS_CUSTOMER' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'INSERT', 'BUSINESS_CONTRACT' );

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'UPDATE', 'BUSINESS_SERVICE' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'UPDATE', 'BUSINESS_CUSTOMER' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'UPDATE', 'BUSINESS_CONTRACT' );

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'DELETE', 'BUSINESS_SERVICE' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'DELETE', 'BUSINESS_CUSTOMER' );
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('ADMINISTRATOR', 'TABLE', 'DELETE', 'BUSINESS_CONTRACT' );



INSERT INTO AUTHORITY_GROUP (AUTHORITY_GROUP, CAPTION) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'BUSINESS_CUSTOMER_ADMIN');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'PAGE', 'ACCESS', 'CUSTOMER');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'SELECT', 'SERVICE_CUSTOMER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'SELECT', 'CUSTOMER_ADDRESS');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'INSERT', 'SERVICE_CUSTOMER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'INSERT', 'CUSTOMER_ADDRESS');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'UPDATE', 'SERVICE_CUSTOMER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'UPDATE', 'CUSTOMER_ADDRESS');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'DELETE', 'SERVICE_CUSTOMER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'DELETE', 'CUSTOMER_ADDRESS');
