CREATE TABLE PERSON (
   PERSON_ID                     INTEGER      NOT NULL,
   FIRST_NAME                    VARCHAR(40)  NOT NULL,
   LAST_NAME                     VARCHAR(40)  NOT NULL,
   PHONE                         VARCHAR(20)  NOT NULL,
   BIRTHDAY                      TIMESTAMP,
   GENDER                        VARCHAR(1),
   NATIONALITY                   VARCHAR(2),
   FACEBOOK_ID                   VARCHAR(80),
   TWITTER_ID                    VARCHAR(80),
   INSTAGRAM_ID                  VARCHAR(80),
   PERSONAL_MAIL                 VARCHAR(80),
   SECRET_QUESTION               VARCHAR(80),
   SECRET_ANSWER                 VARCHAR(80)
);

ALTER TABLE PERSON
  ADD CONSTRAINT PERSON_PK
      PRIMARY KEY (PERSON_ID);

CREATE SEQUENCE PERSON_ID_SEQ START WITH 10 INCREMENT BY 1;



CREATE TABLE USER_ACCOUNT_OWNER (
   USERNAME                      VARCHAR(30)  NOT NULL,
   PERSON_ID                     INTEGER      NOT NULL,
   BEGDA                         TIMESTAMP    NOT NULL
);

ALTER TABLE USER_ACCOUNT_OWNER
  ADD CONSTRAINT USER_ACCOUNT_OWNER_PK
      PRIMARY KEY (USERNAME,PERSON_ID,BEGDA);

ALTER TABLE USER_ACCOUNT_OWNER
  ADD CONSTRAINT USER_ACCOUNT_OWNER_FK1
      FOREIGN KEY (USERNAME)
      REFERENCES USER_ACCOUNT (USERNAME);

ALTER TABLE USER_ACCOUNT_OWNER
  ADD CONSTRAINT USER_ACCOUNT_OWNER_FK2
      FOREIGN KEY (PERSON_ID)
      REFERENCES PERSON (PERSON_ID);

CREATE INDEX USER_ACCOUNT_OWNER_IND1 ON USER_ACCOUNT_OWNER (PERSON_ID);



CREATE TABLE CUSTOMER_EMPLOYEE (
  PERSON_ID            INTEGER   NOT NULL,
  BEGDA                TIMESTAMP NOT NULL,
  ENDDA                TIMESTAMP,
  POSITION             VARCHAR(80),
  EMAIL_ADDRESS        VARCHAR(80),
  WORK_PHONE           VARCHAR(20),
  CELL_PHONE           VARCHAR(20),
  BUSINESS_CUSTOMER_ID VARCHAR(20),
  SERVICE_CUSTOMER_ID  INTEGER
);

ALTER TABLE CUSTOMER_EMPLOYEE
  ADD CONSTRAINT CUSTOMER_EMPLOYEE_PK
      PRIMARY KEY(PERSON_ID, BEGDA);

ALTER TABLE CUSTOMER_EMPLOYEE
  ADD CONSTRAINT CUSTOMER_EMPLOYEE_FK1
      FOREIGN KEY(PERSON_ID)             REFERENCES PERSON            (PERSON_ID);

ALTER TABLE CUSTOMER_EMPLOYEE
  ADD CONSTRAINT CUSTOMER_EMPLOYEE_FK2
      FOREIGN KEY(BUSINESS_CUSTOMER_ID)  REFERENCES BUSINESS_CUSTOMER (BUSINESS_CUSTOMER_ID);

CREATE INDEX CUSTOMER_EMPLOYEE_IND1 ON CUSTOMER_EMPLOYEE (BUSINESS_CUSTOMER_ID);

ALTER TABLE CUSTOMER_EMPLOYEE
  ADD CONSTRAINT CUSTOMER_EMPLOYEE_FK3
      FOREIGN KEY(SERVICE_CUSTOMER_ID)   REFERENCES SERVICE_CUSTOMER  (SERVICE_CUSTOMER_ID);

CREATE INDEX CUSTOMER_EMPLOYEE_IND2 ON CUSTOMER_EMPLOYEE (SERVICE_CUSTOMER_ID);



INSERT INTO DOMAIN_NAME (DOMAIN,KEYSIZE,CAPTION,SORT_BY) VALUES ('GENDER', 1, 'GENDER', 'V');
INSERT INTO DOMAIN_VALUE (DOMAIN,REFVALUE,CAPTION) VALUES ('GENDER', 'F', 'FEMALE');
INSERT INTO DOMAIN_VALUE (DOMAIN,REFVALUE,CAPTION) VALUES ('GENDER', 'M', 'MALE');



INSERT INTO DOMAIN_LOOKUP (DOMAIN, TABLENAME, FIELDNAME) VALUES ('COUNTRY',          'PERSON',          'NATIONALITY');
INSERT INTO DOMAIN_LOOKUP (DOMAIN, TABLENAME, FIELDNAME) VALUES ('GENDER',           'PERSON',          'GENDER');



INSERT INTO MAIN_MENU (MENU, CAPTION, ICON, DISPLAY_ORDER) VALUES ('PERSONNEL',  'PERSONNEL', 'fa-circle', 1000);



INSERT INTO SCREEN_PAGE (PAGENAME, CAPTION, ICON, URL, MENU, DISPLAY_ORDER) VALUES ('PERSON',       'PERSON',       'fa-bars',    'person/search',         'PERSONNEL', 10);



INSERT INTO AUTHORITY_GROUP (AUTHORITY_GROUP, CAPTION) VALUES ('PERSONNEL_ADMIN', 'PERSONNEL_ADMIN');



INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'PAGE', 'ACCESS', 'PERSON');



INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'SELECT', 'PERSON');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'INSERT', 'PERSON');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'UPDATE', 'PERSON');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'DELETE', 'PERSON');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'SELECT', 'USER_ACCOUNT_OWNER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'INSERT', 'USER_ACCOUNT_OWNER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'UPDATE', 'USER_ACCOUNT_OWNER');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP, OBJECT_TYPE, ACTION, KEY_VALUE) VALUES ('PERSONNEL_ADMIN', 'TABLE', 'DELETE', 'USER_ACCOUNT_OWNER');

INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'SELECT', 'CUSTOMER_EMPLOYEE');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'INSERT', 'CUSTOMER_EMPLOYEE');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'UPDATE', 'CUSTOMER_EMPLOYEE');
INSERT INTO OBJECT_AUTHORIZATION (AUTHORITY_GROUP,OBJECT_TYPE,ACTION,KEY_VALUE) VALUES ('BUSINESS_CUSTOMER_ADMIN', 'TABLE', 'DELETE', 'CUSTOMER_EMPLOYEE');


INSERT INTO BUSINESS_SERVICE VALUES('PERSONNEL', 'PERSONNEL MANAGEMENT');
